// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejJ3Vktvlk3WL8Dg3EF4CZJJu83-A9qE',
    appId: '1:893541157084:web:387ba2c0ccb33f6bf7cc19',
    messagingSenderId: '893541157084',
    projectId: 'testassignementapp',
    authDomain: 'testassignementapp.firebaseapp.com',
    storageBucket: 'testassignementapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbioIA3AA-oIn2uXPsFsC1SZ7krP1MYPQ',
    appId: '1:881613481606:android:952bf513fa7f89c0e6d307',
    messagingSenderId: '881613481606',
    projectId: 'fir-techbrothers',
    databaseURL: 'https://fir-techbrothers-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-techbrothers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKK51-75tc5lET7X51kDeiDYUD4QRkQpY',
    appId: '1:881613481606:ios:23d354e5d6617db3e6d307',
    messagingSenderId: '881613481606',
    projectId: 'fir-techbrothers',
    databaseURL: 'https://fir-techbrothers-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-techbrothers.firebasestorage.app',
    iosBundleId: 'com.example.testAssignmentApp',
  );

}